## Упражнения по библиотеке Numpy

In [16]:
import numpy as np
from numpy import loadtxt
import pandas as pd

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [300]:
arr = np.arange(10)
arr[(arr>3) & (arr<=8)]*= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9])

**2.** Заменить максимальный элемент случайного массива на 0

In [187]:
a = np.arange(10)
maxNum = np.amax(a)
np.where(np.isin(a,maxNum), 0, a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [209]:
x = np.array([
    [1, 2, 3, 4],
    [6, 7, 8, 9]
])
flat_array = x.flatten()
y = x.reshape(8,1)
mult = y*flat_array
mult

array([[ 1,  2,  3,  4,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 24, 28, 32, 36],
       [ 6, 12, 18, 24, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 54, 63, 72, 81]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [309]:
A = np.array([
    [1, 9, 4],
    [6, 7, 6],
    [8, 9, 3],
    [1, 9, 5],
    [0, 3, 4],
    [3, 3, 5],
    [3, 6, 8],
    [0, 6, 3]
])

B = np.array([
    [1, 2],
    [6, 7]
])
x = np.intersect1d(A,B)

for index, value in np.ndenumerate(A):
    for j in x:
        if value==j:
            print(index)

(0, 0)
(1, 0)
(1, 1)
(1, 2)
(3, 0)
(6, 1)
(7, 1)


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [349]:
nums = np.random.randint(0,6,(10,3))

for x in range(len(nums)):
    if len(np.unique(nums[x]))>1:
        print(nums[x])

[3 4 2]
[2 5 4]
[1 5 5]
[4 0 5]
[1 3 5]
[3 4 1]
[1 3 1]
[5 5 2]
[0 3 3]
[2 3 3]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [353]:
A = np.array([[1, 2, 3], [4, 5, 6],[1, 2, 3]])
np.unique(A, axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [402]:
#1
x = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
y = x.diagonal()
p = 1
for a in y:
    if a!=0:
        p*=a
print(p)

#2
x = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
y = x.diagonal()
n = y!=0
np.prod(y[n])

3

Задача 2: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
 Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [407]:
#1
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
np.array_equal(np.unique(x),np.unique(y))

#2
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
if sorted(x) == sorted(y):
    print('True')
else:
    ('False')

True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [409]:
#1
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) 
print(x[1:][(x==0)[:-1]].max())

#2
max(x[i] for i in range(i,len(x)) if x[i-1]==0)

5


5

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [159]:
# np.array([2, 3, 5]
#  np.array([3, 3, 1])
# еще подумаю

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [423]:
%%timeit
import timeit
import scipy.spatial
1 #time 10.6 µs ± 36.2 ns per loop
x = np.array([[1, 2, 3], [4, 5, 6],[1, 2, 3]])
y =np.array([[4, 5, 6],[1, 2, 3],[1, 2, 3]])
scipy.spatial.distance.cdist(x,y) 

#2 time 11.7 µs ± 104 ns per loop
x = np.array([[1, 2, 3], [4, 5, 6],[1, 2, 3]])
y =np.array([[4, 5, 6],[1, 2, 3],[1, 2, 3]])
np.linalg.norm(x - y)

11.7 µs ± 104 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [116]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [124]:
average_calories = calorie_stats.mean()
average_calories_prc = average_calories/60
print(average_calories)

106.88311688311688


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [123]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [125]:
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [435]:
nth_percentile = np.percentile(calorie_stats, 25, axis=0)
nth_percentile_2 = np.percentile(calorie_stats, 50, axis=0)
nth_percentile_3 = np.percentile(calorie_stats, 75, axis=0)
nth_percentile_4 = np.percentile(calorie_stats, 100, axis=0)

nth_percentile

100.0

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [142]:
size = calorie_stats.size
cond_size =np.count_nonzero(calorie_stats >60)
more_calories = (cond_size/size)*100
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [143]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [438]:
# ввиду вероятности сильных выбросов данных при определении наиболее популярного значения в выборке 
# и сопоставления его с анализируемым значением стоит обратить внимание не на среднее значение, которое
# может давать не совсем корректные результаты по причине размаха данных и по причине 
# результата стандартного отклонения, которое показывает, что данные в выборке в среднем
# отклоняются от значения среднего значения на 19,36 (не самое большое значение отклонения, но чем это значение
# больше 0, тем меньше стоит доверять среднему), а на медиану, которая показывает 
# наиболее центральное значение среди всей выборки и в нашем примере медиана равна 110. 
# 96 процентов марок хлопьев конкурентов производят хлопья, в которых калорий больше чем 60, то есть хлопья
# CrunchieMunchies находятся в выигрышном меньшинстве по содержанию калорий по сравнению с конкуретами.
# То есть хлопья CrunchieMunchies с содержанием 60 калорий в одной порции значительно выигрывают 
# в плане полезности.